name: Build ImmortalWrt

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 安装必要的依赖
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt full-upgrade -y $BPO_FLAG
        sudo apt install -y $BPO_FLAG ack antlr3 asciidoc autoconf automake autopoint binutils bison \
        build-essential bzip2 ccache cmake cpio curl device-tree-compiler ecj fakeroot \
        fastjar flex gawk gettext genisoimage git gnutls-dev gperf haveged help2man \
        intltool irqbalance jq libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev \
        libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libreadline-dev libssl-dev \
        libtool libyaml-dev libz-dev lrzsz msmtp nano ninja-build p7zip p7zip-full patch \
        pkgconf libpython3-dev python3 python3-pip python3-cryptography python3-docutils \
        python3-ply python3-pyelftools python3-requests qemu-utils quilt re2c rsync scons \
        sharutils squashfs-tools subversion swig texinfo uglifyjs unzip vim wget xmlto \
        zlib1g-dev zstd xxd build-essential libncurses5-dev gawk git gettext unzip file libssl-dev wget python3 python3-distutils tmate python3-pip
        pip3 install pyelftools $VERSION_PACKAGE 

    # 启动 tmate 会话
    - name: Start tmate session
      run: |
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        echo "SSH connection: $(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')"
        echo "Web connection: $(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')"



        

    # 设置 ImmortalWrt
    - name: Build ImmortalWrt
      run: |
        git clone https://github.com/immortalwrt/immortalwrt.git
        cd immortalwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    # 输出 tmate 连接信息
    - name: Output tmate connection info
      run: |
        cd immortalwrt
        echo "SSH connection: $(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')"
        echo "Web connection: $(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')"

    # 等待用户完成 tmate 会话
    - name: Wait for tmate session to complete
      run: |
        echo "Waiting for tmate session to complete. Please disconnect from the session to continue."
        tmate -S /tmp/tmate.sock wait tmate-exit

    # 编译 ImmortalWrt
    - name: Build ImmortalWrt
      run: |
        cd immortalwrt
        make -j$(nproc)

    # 打包固件
    - name: Package firmware
      run: |
        cd immortalwrt/bin/targets
        tar -czf firmware.tar.gz *

    # 上传固件到 GitHub Releases
    - name: Upload firmware to GitHub Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: immortalwrt/bin/targets/firmware.tar.gz
        asset_name: firmware.tar.gz
        asset_content_type: application/gzip