name: Build ImmortalWrt

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 安装必要的依赖
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git gettext unzip file libssl-dev wget python3 python3-distutils tmate

    # 启动 tmate 会话
    - name: Start tmate session
      run: |
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        echo "SSH connection: $(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')"
        echo "Web connection: $(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')"

    # 输出 tmate 连接信息
    - name: Output tmate connection info
      run: |
        echo "SSH connection: $(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')"
        echo "Web connection: $(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')"

    # 编译 ImmortalWrt
    - name: Build ImmortalWrt
      run: |
        git clone https://github.com/immortalwrt/immortalwrt.git
        cd immortalwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make menuconfig  # 可根据需要调整配置
        make -j$(nproc)